"""
Correlation Engine Module
=========================
This module handles multi-event correlation to detect complex attack patterns
that span multiple logs over time (e.g., brute force followed by successful login).

Uses MongoDB for state management with TTL indexes for automatic cleanup.

Key Features:
- Sliding window correlation
- Per-IP and per-user state tracking
- Multi-step attack pattern detection
- Automatic state expiration
"""

import os
from datetime import datetime, timedelta
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field
from dotenv import load_dotenv

load_dotenv()

try:
    from pymongo import MongoClient, ASCENDING
    from pymongo.errors import ConnectionFailure
    MONGO_AVAILABLE = True
except ImportError:
    MONGO_AVAILABLE = False
    print("Warning: pymongo not installed. Using in-memory fallback.")

@dataclass
# user state
class UserState:
    """
    Represents the tracked state of a user/IP for correlation.
    """
    identifier: str
    identifier_type: str
    failed_login_count: int = 0
    last_failed_login: Optional[str] = None
    successful_login_after_failures: bool = False
    flagged_as_suspicious: bool = False
    triggered_rules: List[str] = field(default_factory=list)
    events: List[Dict] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    updated_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    
    # to dict
    def to_dict(self) -> Dict:
        return {
            "identifier": self.identifier,
            "identifier_type": self.identifier_type,
            "failed_login_count": self.failed_login_count,
            "last_failed_login": self.last_failed_login,
            "successful_login_after_failures": self.successful_login_after_failures,
            "flagged_as_suspicious": self.flagged_as_suspicious,
            "triggered_rules": self.triggered_rules,
            "events": self.events[-10:],
            "created_at": self.created_at,
            "updated_at": self.updated_at
        }

@dataclass 
# correlation alert
class CorrelationAlert:
    """
    Alert generated by the correlation engine for multi-step attacks.
    """
    pattern_id: str
    pattern_name: str
    severity: str
    description: str
    identifier: str
    identifier_type: str
    event_chain: List[Dict]
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    
    # to dict
    def to_dict(self) -> Dict:
        return {
            "pattern_id": self.pattern_id,
            "pattern_name": self.pattern_name,
            "severity": self.severity,
            "description": self.description,
            "identifier": self.identifier,
            "identifier_type": self.identifier_type,
            "event_chain": self.event_chain,
            "timestamp": self.timestamp,
            "alert_type": "correlation"
        }

# state manager
class StateManager:
    """
    Manages user/IP states in MongoDB for correlation.
    Falls back to in-memory storage if MongoDB is unavailable.
    """
    
    def __init__(self, mongo_uri: str = None, db_name: str = None):
        self.mongo_uri = mongo_uri or os.getenv("MONGO_URI", "mongodb://localhost:27017/")
        self.db_name = db_name or os.getenv("MONGO_DB_NAME", "incident_detection")
        self.client = None
        self.db = None
        self.states_collection = None
        self.use_memory = not MONGO_AVAILABLE
        self.memory_states: Dict[str, UserState] = {}
        
        if not self.use_memory:
            self._connect()
    
    # connect
    def _connect(self):
        """Establish connection to MongoDB."""
        try:
            self.client = MongoClient(self.mongo_uri, serverSelectionTimeoutMS=5000)
            self.client.admin.command('ping')
            self.db = self.client[self.db_name]
            self.states_collection = self.db["states"]
            
            self.states_collection.create_index(
                "updated_at",
                expireAfterSeconds=3600
            )
            
            print(f"Connected to MongoDB: {self.db_name}")
        except Exception as e:
            print(f"MongoDB connection failed: {e}. Using in-memory storage.")
            self.use_memory = True
    
    # get state
    def get_state(self, identifier: str, identifier_type: str = "ip") -> Optional[UserState]:
        """
        Get the current state for an IP or user.
        """
        key = f"{identifier_type}:{identifier}"
        
        if self.use_memory:
            return self.memory_states.get(key)
        
        doc = self.states_collection.find_one({"_id": key})
        if doc:
            return UserState(
                identifier=doc["identifier"],
                identifier_type=doc["identifier_type"],
                failed_login_count=doc.get("failed_login_count", 0),
                last_failed_login=doc.get("last_failed_login"),
                successful_login_after_failures=doc.get("successful_login_after_failures", False),
                flagged_as_suspicious=doc.get("flagged_as_suspicious", False),
                triggered_rules=doc.get("triggered_rules", []),
                events=doc.get("events", []),
                created_at=doc.get("created_at", ""),
                updated_at=doc.get("updated_at", "")
            )
        return None
    
    # update state
    def update_state(self, state: UserState) -> None:
        """
        Update or insert a state in the database.
        """
        key = f"{state.identifier_type}:{state.identifier}"
        state.updated_at = datetime.utcnow().isoformat()
        
        if self.use_memory:
            self.memory_states[key] = state
            return
        
        doc = state.to_dict()
        doc["_id"] = key
        self.states_collection.replace_one(
            {"_id": key},
            doc,
            upsert=True
        )
    
    # add event to state
    def add_event_to_state(self, identifier: str, identifier_type: str, event: Dict) -> UserState:
        """
        Add an event to a state's event history.
        """
        state = self.get_state(identifier, identifier_type)
        if state is None:
            state = UserState(identifier=identifier, identifier_type=identifier_type)
        
        event_summary = {
            "timestamp": event.get("timestamp", ""),
            "event_name": event.get("event_name", ""),
            "event_type": event.get("event_type", ""),
            "status": event.get("status", ""),
            "source_ip": event.get("source_ip", "")
        }
        state.events.append(event_summary)
        
        if len(state.events) > 20:
            state.events = state.events[-20:]
        
        self.update_state(state)
        return state
    
    # clear state
    def clear_state(self, identifier: str, identifier_type: str = "ip") -> None:
        """
        Clear a state (e.g., after an attack pattern is fully detected).
        """
        key = f"{identifier_type}:{identifier}"
        
        if self.use_memory:
            self.memory_states.pop(key, None)
            return
        
        self.states_collection.delete_one({"_id": key})

# correlator
class Correlator:
    """
    The main correlation engine that detects multi-step attack patterns.
    """
    
    BRUTE_FORCE_THRESHOLD = 5
    BRUTE_FORCE_WINDOW_MINUTES = 10
    
    def __init__(self, state_manager: StateManager = None):
        self.state_manager = state_manager or StateManager()
    
    # process event
    def process_event(self, normalized_log: Dict) -> List[CorrelationAlert]:
        """
        Process a normalized log event and check for correlation patterns.
        
        Returns:
            List of CorrelationAlerts if patterns are detected
        """
        alerts = []
        
        source_ip = normalized_log.get("source_ip", "")
        actor_id = normalized_log.get("actor_id", "")
        event_name = normalized_log.get("event_name", "").lower()
        status = normalized_log.get("status", "")
        
        if source_ip:
            ip_alerts = self._process_for_identifier(
                normalized_log, source_ip, "ip"
            )
            alerts.extend(ip_alerts)
        
        if actor_id and actor_id != source_ip:
            user_alerts = self._process_for_identifier(
                normalized_log, actor_id, "user"
            )
            alerts.extend(user_alerts)
        
        return alerts
    
    # process for identifier
    def _process_for_identifier(
        self, 
        log: Dict, 
        identifier: str, 
        identifier_type: str
    ) -> List[CorrelationAlert]:
        """
        Process an event for a specific identifier (IP or user).
        """
        alerts = []
        
        state = self.state_manager.add_event_to_state(identifier, identifier_type, log)
        
        event_name = log.get("event_name", "").lower()
        status = log.get("status", "")
        
        if self._is_login_event(event_name):
            if status == "failure":
                state.failed_login_count += 1
                state.last_failed_login = log.get("timestamp", "")
                
                if state.failed_login_count >= self.BRUTE_FORCE_THRESHOLD:
                    state.flagged_as_suspicious = True
                    
                    if "AUTH_BRUTE_FORCE" not in state.triggered_rules:
                        state.triggered_rules.append("AUTH_BRUTE_FORCE")
                        alerts.append(CorrelationAlert(
                            pattern_id="AUTH_BRUTE_FORCE",
                            pattern_name="Brute Force Attack Detected",
                            severity="HIGH",
                            description=f"Detected {state.failed_login_count} failed login attempts from {identifier}",
                            identifier=identifier,
                            identifier_type=identifier_type,
                            event_chain=state.events[-state.failed_login_count:]
                        ))
            
            elif status == "success":
                if state.flagged_as_suspicious or state.failed_login_count >= 3:
                    state.successful_login_after_failures = True
                    
                    if "AUTH_SUCCESS_AFTER_FAILURES" not in state.triggered_rules:
                        state.triggered_rules.append("AUTH_SUCCESS_AFTER_FAILURES")
                        alerts.append(CorrelationAlert(
                            pattern_id="AUTH_SUCCESS_AFTER_FAILURES",
                            pattern_name="Successful Login After Multiple Failures",
                            severity="CRITICAL",
                            description=f"Potential breach: Success after {state.failed_login_count} failed attempts from {identifier}",
                            identifier=identifier,
                            identifier_type=identifier_type,
                            event_chain=state.events[-10:]
                        ))
                
                state.failed_login_count = 0
        
        if state.successful_login_after_failures:
            if self._is_privilege_event(event_name):
                if "PATTERN_BREACH_AND_PERSIST" not in state.triggered_rules:
                    state.triggered_rules.append("PATTERN_BREACH_AND_PERSIST")
                    alerts.append(CorrelationAlert(
                        pattern_id="PATTERN_BREACH_AND_PERSIST",
                        pattern_name="Breach and Persistence Pattern",
                        severity="CRITICAL",
                        description=f"Privilege modification detected after breach from {identifier}",
                        identifier=identifier,
                        identifier_type=identifier_type,
                        event_chain=state.events[-10:]
                    ))
            
            if self._is_data_access_event(event_name):
                if "PATTERN_DATA_EXFILTRATION" not in state.triggered_rules:
                    state.triggered_rules.append("PATTERN_DATA_EXFILTRATION")
                    alerts.append(CorrelationAlert(
                        pattern_id="PATTERN_DATA_EXFILTRATION",
                        pattern_name="Potential Data Exfiltration",
                        severity="CRITICAL",
                        description=f"Data access detected after breach from {identifier}",
                        identifier=identifier,
                        identifier_type=identifier_type,
                        event_chain=state.events[-10:]
                    ))
        
        if self._is_logging_disabled_event(event_name):
            state.triggered_rules.append("RES_LOGGING_DISABLED")
        
        if "RES_LOGGING_DISABLED" in state.triggered_rules:
            if self._is_deletion_event(event_name):
                if "PATTERN_COVER_TRACKS" not in state.triggered_rules:
                    state.triggered_rules.append("PATTERN_COVER_TRACKS")
                    alerts.append(CorrelationAlert(
                        pattern_id="PATTERN_COVER_TRACKS",
                        pattern_name="Evidence Destruction Pattern",
                        severity="CRITICAL",
                        description=f"Resource deletion after logging disabled by {identifier}",
                        identifier=identifier,
                        identifier_type=identifier_type,
                        event_chain=state.events[-10:]
                    ))
        
        self.state_manager.update_state(state)
        
        return alerts
    
    # is login event
    def _is_login_event(self, event_name: str) -> bool:
        """Check if the event is a login attempt."""
        login_keywords = [
            "login", "signin", "authenticate", "consolelogin",
            "getsessiontoken", "assumerole"
        ]
        return any(kw in event_name for kw in login_keywords)
    
    # is privilege event
    def _is_privilege_event(self, event_name: str) -> bool:
        """Check if the event involves privilege changes."""
        priv_keywords = [
            "policy", "role", "permission", "createuser", "createaccesskey",
            "attachpolicy", "putrole", "setiampolicy"
        ]
        return any(kw in event_name for kw in priv_keywords)
    
    # is data access event
    def _is_data_access_event(self, event_name: str) -> bool:
        """Check if the event involves data access."""
        data_keywords = [
            "getobject", "download", "read", "listobjects", "query",
            "export", "copy", "sync"
        ]
        return any(kw in event_name for kw in data_keywords)
    
    # is logging disabled event
    def _is_logging_disabled_event(self, event_name: str) -> bool:
        """Check if the event disables logging."""
        log_keywords = [
            "stoplogging", "deletetrail", "updatetrail", "disablelogs"
        ]
        return any(kw in event_name for kw in log_keywords)
    
    # is deletion event
    def _is_deletion_event(self, event_name: str) -> bool:
        """Check if the event is a resource deletion."""
        delete_keywords = [
            "delete", "terminate", "remove", "destroy", "drop"
        ]
        return any(kw in event_name for kw in delete_keywords)

if __name__ == "__main__":
    import json
    
    print("Testing Correlation Engine...")
    
    correlator = Correlator()
    
    test_events = [
        {"event_name": "ConsoleLogin", "status": "failure", "source_ip": "192.168.1.100", "actor_id": "attacker", "timestamp": "2024-01-15T10:00:00Z"},
        {"event_name": "ConsoleLogin", "status": "failure", "source_ip": "192.168.1.100", "actor_id": "attacker", "timestamp": "2024-01-15T10:00:30Z"},
        {"event_name": "ConsoleLogin", "status": "failure", "source_ip": "192.168.1.100", "actor_id": "attacker", "timestamp": "2024-01-15T10:01:00Z"},
        {"event_name": "ConsoleLogin", "status": "failure", "source_ip": "192.168.1.100", "actor_id": "attacker", "timestamp": "2024-01-15T10:01:30Z"},
        {"event_name": "ConsoleLogin", "status": "failure", "source_ip": "192.168.1.100", "actor_id": "attacker", "timestamp": "2024-01-15T10:02:00Z"},
        {"event_name": "ConsoleLogin", "status": "success", "source_ip": "192.168.1.100", "actor_id": "attacker", "timestamp": "2024-01-15T10:03:00Z"},
        {"event_name": "CreateAccessKey", "status": "success", "source_ip": "192.168.1.100", "actor_id": "attacker", "timestamp": "2024-01-15T10:04:00Z"},
    ]
    
    print("\nSimulating attack sequence:")
    for event in test_events:
        print(f"  Processing: {event['event_name']} ({event['status']})")
        alerts = correlator.process_event(event)
        for alert in alerts:
            print(f"     ALERT: [{alert.severity}] {alert.pattern_name}")
